---
title: "Beginning Crimes"
author: "Kaeshev ALapati"
date: "2023-02-02"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Libraries:
```{r}
library(tidyverse)
library(readxl)
library(knitr)
library(ggplot2)
library(sqldf)
```

Reading in Data:
```{r}
crime_data <- read_csv("data/Crimes_-_2001_to_Present.csv")
head(crime_data)
```
```{r}
temperature_data <- read_csv("data/Chicago area average temperature data.csv")
temperature_data <- temperature_data %>% pivot_longer(!Year, names_to = "month", values_to = "temp")
#temperature_data = temperature_data %>% mutate(date = as.Date(Year month))
head(temperature_data)
```
Important bits of crime data:
```{r}
important_crime_data <- crime_data %>% select(Date, 'Primary Type', Arrest, Domestic, Year)
```
Graphing Data:
```{r}
crims <- c()

for (num in 2001:2021) {
  append(crims, sum(crime_data$Year == num))
  # print(glue("{num}: {sum(crime_data$Year == num)}"))
}

print(crims)

# crimes_per_year <- data.frame(2001:2021, crims)

# print(crimes_per_year)

# ggplot(important_crime_data, aes(x = Year, y = sum(crime_data$Year == num))) +
#   geom_bar()

# ggplot(important_crime_data, aes(x=(Date))) + geom_density()

```
